<?php

namespace Tests\Feature;

use App\Models\CompanyProfile;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class CompanyProfileSettingsTest extends TestCase
{
    use RefreshDatabase;

    public function test_admin_can_update_global_company_settings(): void
    {
        $admin = User::factory()->create([
            'role' => 'admin',
            'is_active' => true,
        ]);

        $company = CompanyProfile::create(CompanyProfile::defaults());

        $response = $this->actingAs($admin)->put(route('company-profiles.update', $company), [
            'name' => 'Global QuoteFlow Pte Ltd',
            'registration_number' => '202600001G',
            'email' => 'finance@global-quoteflow.test',
            'phone' => '+65 6123 4567',
            'address' => "10 Business Street\nSingapore 048000",
            'tagline' => 'Business documents without borders.',
            'primary_color' => '#123456',
            'accent_color' => '#654321',
            'country' => 'Singapore',
            'timezone' => 'Asia/Singapore',
            'base_currency' => 'SGD',
            'currency_display' => 'symbol_with_code',
            'currency_symbol_override' => 'S$',
            'date_format' => 'Y-m-d',
            'number_format' => 'en-SG',
            'tax_label' => 'GST',
            'tax_registration_label' => 'GST Registration No.',
            'tax_registration_number' => 'M90000000X',
            'default_tax_rate' => '9.00',
            'delivery_gap_alert_percent' => '18.00',
            'received_not_invoiced_alert_percent' => '7.50',
            'delivery_gap_alert_amount' => '5000.00',
            'received_not_invoiced_alert_amount' => '2500.00',
            'payment_instructions' => "Bank transfer only\nUse invoice number as payment reference",
            'pdf_footer' => 'This document is generated by QuoteFlow for Singapore operations.',
        ]);

        $response->assertRedirect(route('company-profiles.index'));

        $company->refresh();

        $this->assertSame('Singapore', $company->displayCountry());
        $this->assertSame('Asia/Singapore', $company->displayTimezone());
        $this->assertSame('SGD', $company->baseCurrency());
        $this->assertSame('symbol_with_code', $company->currencyDisplay());
        $this->assertSame('S$', $company->currencySymbol('SGD'));
        $this->assertSame('Y-m-d', $company->dateFormat());
        $this->assertSame('en-SG', $company->numberFormat());
        $this->assertSame('GST', $company->taxLabel());
        $this->assertSame('GST Registration No.', $company->taxRegistrationLabel());
        $this->assertSame(9.0, $company->defaultTaxRate());
        $this->assertSame(18.0, $company->deliveryGapAlertPercent());
        $this->assertSame(7.5, $company->receivedNotInvoicedAlertPercent());
        $this->assertSame(5000.0, $company->deliveryGapAlertAmount());
        $this->assertSame(2500.0, $company->receivedNotInvoicedAlertAmount());
        $this->assertSame([
            'Bank transfer only',
            'Use invoice number as payment reference',
        ], $company->paymentInstructionLines());
    }

    public function test_first_run_company_profile_defaults_are_neutral(): void
    {
        $company = CompanyProfile::active();

        $this->assertSame('Your Company Name', $company->displayName());
        $this->assertSame('', $company->displayTagline());
        $this->assertSame('Other', $company->displayCountry());
        $this->assertSame('UTC', $company->displayTimezone());
        $this->assertSame('USD', $company->baseCurrency());
        $this->assertSame('code', $company->currencyDisplay());
        $this->assertSame('USD 1,234.56', $company->formatMoney(1234.56));
        $this->assertSame(25.0, $company->deliveryGapAlertPercent());
        $this->assertSame(10.0, $company->receivedNotInvoicedAlertPercent());
        $this->assertSame(0.0, $company->deliveryGapAlertAmount());
        $this->assertSame(0.0, $company->receivedNotInvoicedAlertAmount());
        $this->assertSame('YC', $company->initials());
        $this->assertSame('', $company->logoUrl());
        $this->assertSame('', $company->logoPathForPdf());
    }

    public function test_logo_less_company_profile_surfaces_render_initials_without_empty_images(): void
    {
        $admin = User::factory()->create([
            'role' => 'admin',
            'is_active' => true,
        ]);

        $login = $this->get(route('login'));

        $login->assertOk();
        $login->assertSee('company-logo-placeholder', false);
        $login->assertSee('YC');
        $login->assertDontSee('src=""', false);

        $company = CompanyProfile::create(CompanyProfile::defaults());

        $profile = $this->actingAs($admin)->get(route('company-profiles.index'));

        $profile->assertOk();
        $profile->assertSee('company-logo-placeholder', false);
        $profile->assertSee('YC');
        $profile->assertDontSee('src=""', false);

        $edit = $this->actingAs($admin)->get(route('company-profiles.edit', $company));

        $edit->assertOk();
        $edit->assertSee('company-logo-placeholder', false);
        $edit->assertDontSee('src=""', false);

        $dashboard = $this->actingAs($admin)->get(route('dashboard'));

        $dashboard->assertOk();
        $dashboard->assertSee('Your Company Name');
        $dashboard->assertSee('company-logo-placeholder', false);
        $dashboard->assertDontSee('src=""', false);
    }

    public function test_company_profile_page_shows_global_document_settings(): void
    {
        $admin = User::factory()->create([
            'role' => 'admin',
            'is_active' => true,
        ]);

        CompanyProfile::create(array_merge(CompanyProfile::defaults(), [
            'name' => 'Global QuoteFlow Pte Ltd',
            'country' => 'Singapore',
            'timezone' => 'Asia/Singapore',
            'base_currency' => 'SGD',
            'date_format' => 'Y-m-d',
            'number_format' => 'en-SG',
            'tax_label' => 'GST',
            'tax_registration_label' => 'GST Registration No.',
            'tax_registration_number' => 'M90000000X',
            'default_tax_rate' => 9,
            'delivery_gap_alert_percent' => 18,
            'received_not_invoiced_alert_percent' => 7.5,
            'delivery_gap_alert_amount' => 5000,
            'received_not_invoiced_alert_amount' => 2500,
            'payment_instructions' => 'Use invoice number as payment reference',
            'pdf_footer' => 'Singapore operations footer',
        ]));

        $response = $this->actingAs($admin)->get(route('company-profiles.index'));

        $response->assertOk();
        $response->assertSee('Global document settings');
        $response->assertSee('Singapore');
        $response->assertSee('Asia/Singapore');
        $response->assertSee('SGD');
        $response->assertSee('Singapore / English - 1,234.56');
        $response->assertSee('GST');
        $response->assertSee('9.00%');
        $response->assertSee('M90000000X');
        $response->assertSee('Project control settings');
        $response->assertSee('Delivery billing alert levels');
        $response->assertSee('18.00%');
        $response->assertSee('7.50%');
        $response->assertSee('SGD 5,000.00');
        $response->assertSee('SGD 2,500.00');
        $response->assertSee('Use invoice number as payment reference');
        $response->assertSee('Singapore operations footer');
    }

    public function test_company_profile_edit_form_exposes_country_defaults_and_friendly_number_formats(): void
    {
        $admin = User::factory()->create([
            'role' => 'admin',
            'is_active' => true,
        ]);

        $company = CompanyProfile::create(CompanyProfile::defaults());

        $response = $this->actingAs($admin)->get(route('company-profiles.edit', $company));

        $response->assertOk();
        $response->assertSee('enctype="multipart/form-data"', false);
        $response->assertSee('data-company-logo-preview', false);
        $response->assertSee('data-company-logo-input', false);
        $response->assertSee('data-company-logo-preview-status', false);
        $response->assertSee('data-country-select', false);
        $response->assertSee('data-country-default-field="timezone"', false);
        $response->assertSee('data-country-default-field="currency_display"', false);
        $response->assertSee('data-country-default-field="currency_symbol_override"', false);
        $response->assertSee('data-country-default-field="tax_registration_label"', false);
        $response->assertSee('name="delivery_gap_alert_percent"', false);
        $response->assertSee('name="received_not_invoiced_alert_percent"', false);
        $response->assertSee('name="delivery_gap_alert_amount"', false);
        $response->assertSee('name="received_not_invoiced_alert_amount"', false);
        $response->assertSee('Project control settings');
        $response->assertSee('Delivery billing alert levels');
        $response->assertSee('Customer unbilled / not yet received alert %');
        $response->assertSee('Received not invoiced alert %');
        $response->assertSee('Customer unbilled / not yet received amount alert');
        $response->assertSee('Received not invoiced amount alert');
        $response->assertSee('Currency display');
        $response->assertSee('Currency symbol override');
        $response->assertSee('Currency symbol - RM 1,234.56');
        $response->assertSee('Symbol and code - RM 1,234.56 (MYR)');
        $response->assertSee('name="currency_display"', false);
        $response->assertSee('name="currency_symbol_override"', false);
        $response->assertSee('Malaysia / English - 1,234.56');
        $response->assertSee('Singapore / English - 1,234.56');
        $response->assertSee('United States / English - 1,234.56');
        $response->assertSee('Asia/Singapore');
        $response->assertSee('SGD');
        $response->assertSee('GST Registration No.');
        $response->assertSee('Tax ID', false);
        $response->assertSee('EIN', false);
        $response->assertSee('Sales tax');
    }

    public function test_company_profile_formats_dates_numbers_money_and_percentages(): void
    {
        $company = new CompanyProfile(array_merge(CompanyProfile::defaults(), [
            'base_currency' => 'EUR',
            'date_format' => 'Y-m-d',
            'number_format' => 'de-DE',
        ]));

        $this->assertSame('2026-05-20', $company->formatDate('2026-05-20'));
        $this->assertSame('-', $company->formatDate(null));
        $this->assertSame('1.234,56', $company->formatNumber(1234.56));
        $this->assertSame('EUR 1.234,56', $company->formatMoney(1234.56));
        $this->assertSame('USD 1.234,56', $company->formatMoney(1234.56, 'USD'));
        $this->assertSame('9,00%', $company->formatPercent(9));
    }

    public function test_company_profile_formats_expanded_number_formats(): void
    {
        $india = new CompanyProfile(array_merge(CompanyProfile::defaults(), [
            'base_currency' => 'INR',
            'currency_display' => 'code',
            'number_format' => 'en-IN',
        ]));
        $switzerland = new CompanyProfile(array_merge(CompanyProfile::defaults(), [
            'base_currency' => 'CHF',
            'currency_display' => 'code',
            'number_format' => 'de-CH',
        ]));
        $japan = new CompanyProfile(array_merge(CompanyProfile::defaults(), [
            'base_currency' => 'JPY',
            'currency_display' => 'code',
            'number_format' => 'ja-JP',
        ]));
        $korea = new CompanyProfile(array_merge(CompanyProfile::defaults(), [
            'base_currency' => 'KRW',
            'currency_display' => 'code',
            'number_format' => 'ko-KR',
        ]));

        $this->assertSame('12,34,567.89', $india->formatNumber(1234567.89));
        $this->assertSame('INR 12,34,567.89', $india->formatMoney(1234567.89));
        $this->assertSame("CHF 1'234.56", $switzerland->formatMoney(1234.56));
        $this->assertSame('JPY 1,235', $japan->formatMoney(1234.56));
        $this->assertSame('KRW 1,235', $korea->formatMoney(1234.56));
    }

    public function test_malaysia_money_defaults_to_rm_symbol_when_company_is_malaysian(): void
    {
        $company = new CompanyProfile(array_merge(CompanyProfile::defaults(), [
            'country' => 'Malaysia',
            'timezone' => 'Asia/Kuala_Lumpur',
            'base_currency' => 'MYR',
            'currency_display' => null,
            'currency_symbol_override' => null,
            'number_format' => 'en-MY',
        ]));

        $this->assertSame('symbol', $company->currencyDisplay());
        $this->assertSame('RM', $company->currencySymbol('MYR'));
        $this->assertSame('RM 1,234.56', $company->formatMoney(1234.56));
    }

    public function test_company_profile_can_use_symbol_and_code_money_display(): void
    {
        $company = new CompanyProfile(array_merge(CompanyProfile::defaults(), [
            'base_currency' => 'MYR',
            'currency_display' => 'symbol_with_code',
            'currency_symbol_override' => 'RM',
            'number_format' => 'en-MY',
        ]));

        $this->assertSame('RM (MYR)', $company->currencyDisplayLabel());
        $this->assertSame('RM 1,234.56 (MYR)', $company->formatMoney(1234.56));
    }
}
