<?php

namespace Tests\Feature;

use App\Models\CompanyProfile;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class CompanyProfileSettingsTest extends TestCase
{
    use RefreshDatabase;

    public function test_admin_can_update_global_company_settings(): void
    {
        $admin = User::factory()->create([
            'role' => 'admin',
            'is_active' => true,
        ]);

        $company = CompanyProfile::create(CompanyProfile::defaults());

        $response = $this->actingAs($admin)->put(route('company-profiles.update', $company), [
            'name' => 'Global QuoteFlow Pte Ltd',
            'registration_number' => '202600001G',
            'email' => 'finance@global-quoteflow.test',
            'phone' => '+65 6123 4567',
            'address' => "10 Business Street\nSingapore 048000",
            'tagline' => 'Business documents without borders.',
            'primary_color' => '#123456',
            'accent_color' => '#654321',
            'country' => 'Singapore',
            'timezone' => 'Asia/Singapore',
            'base_currency' => 'SGD',
            'date_format' => 'Y-m-d',
            'number_format' => 'en-SG',
            'tax_label' => 'GST',
            'tax_registration_label' => 'GST Registration No.',
            'tax_registration_number' => 'M90000000X',
            'default_tax_rate' => '9.00',
            'payment_instructions' => "Bank transfer only\nUse invoice number as payment reference",
            'pdf_footer' => 'This document is generated by QuoteFlow for Singapore operations.',
        ]);

        $response->assertRedirect(route('company-profiles.index'));

        $company->refresh();

        $this->assertSame('Singapore', $company->displayCountry());
        $this->assertSame('Asia/Singapore', $company->displayTimezone());
        $this->assertSame('SGD', $company->baseCurrency());
        $this->assertSame('Y-m-d', $company->dateFormat());
        $this->assertSame('en-SG', $company->numberFormat());
        $this->assertSame('GST', $company->taxLabel());
        $this->assertSame('GST Registration No.', $company->taxRegistrationLabel());
        $this->assertSame(9.0, $company->defaultTaxRate());
        $this->assertSame([
            'Bank transfer only',
            'Use invoice number as payment reference',
        ], $company->paymentInstructionLines());
    }

    public function test_company_profile_page_shows_global_document_settings(): void
    {
        $admin = User::factory()->create([
            'role' => 'admin',
            'is_active' => true,
        ]);

        CompanyProfile::create(array_merge(CompanyProfile::defaults(), [
            'name' => 'Global QuoteFlow Pte Ltd',
            'country' => 'Singapore',
            'timezone' => 'Asia/Singapore',
            'base_currency' => 'SGD',
            'date_format' => 'Y-m-d',
            'number_format' => 'en-SG',
            'tax_label' => 'GST',
            'tax_registration_label' => 'GST Registration No.',
            'tax_registration_number' => 'M90000000X',
            'default_tax_rate' => 9,
            'payment_instructions' => 'Use invoice number as payment reference',
            'pdf_footer' => 'Singapore operations footer',
        ]));

        $response = $this->actingAs($admin)->get(route('company-profiles.index'));

        $response->assertOk();
        $response->assertSee('Global document settings');
        $response->assertSee('Singapore');
        $response->assertSee('Asia/Singapore');
        $response->assertSee('SGD');
        $response->assertSee('Singapore / English - 1,234.56');
        $response->assertSee('GST');
        $response->assertSee('9.00%');
        $response->assertSee('M90000000X');
        $response->assertSee('Use invoice number as payment reference');
        $response->assertSee('Singapore operations footer');
    }

    public function test_company_profile_edit_form_exposes_country_defaults_and_friendly_number_formats(): void
    {
        $admin = User::factory()->create([
            'role' => 'admin',
            'is_active' => true,
        ]);

        $company = CompanyProfile::create(CompanyProfile::defaults());

        $response = $this->actingAs($admin)->get(route('company-profiles.edit', $company));

        $response->assertOk();
        $response->assertSee('data-country-select', false);
        $response->assertSee('data-country-default-field="timezone"', false);
        $response->assertSee('data-country-default-field="tax_registration_label"', false);
        $response->assertSee('Malaysia / English - 1,234.56');
        $response->assertSee('Singapore / English - 1,234.56');
        $response->assertSee('United States / English - 1,234.56');
        $response->assertSee('Asia/Singapore');
        $response->assertSee('SGD');
        $response->assertSee('GST Registration No.');
        $response->assertSee('Tax ID / EIN');
        $response->assertSee('Sales tax');
    }

    public function test_company_profile_formats_dates_numbers_money_and_percentages(): void
    {
        $company = new CompanyProfile(array_merge(CompanyProfile::defaults(), [
            'base_currency' => 'EUR',
            'date_format' => 'Y-m-d',
            'number_format' => 'de-DE',
        ]));

        $this->assertSame('2026-05-20', $company->formatDate('2026-05-20'));
        $this->assertSame('-', $company->formatDate(null));
        $this->assertSame('1.234,56', $company->formatNumber(1234.56));
        $this->assertSame('EUR 1.234,56', $company->formatMoney(1234.56));
        $this->assertSame('USD 1.234,56', $company->formatMoney(1234.56, 'USD'));
        $this->assertSame('9,00%', $company->formatPercent(9));
    }
}
