<?php

namespace Tests\Feature;

use App\Models\CompanyProfile;
use App\Models\Customer;
use App\Models\Document;
use App\Models\DocumentSequence;
use App\Models\Product;
use App\Models\Supplier;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Artisan;
use Symfony\Component\Console\Tester\CommandTester;
use Tests\TestCase;

class SingleCompanyReadinessCommandTest extends TestCase
{
    use RefreshDatabase;

    public function test_ready_single_company_setup_passes_readiness_checks(): void
    {
        $this->prepareReadySingleCompany();

        [$exitCode, $output] = $this->runReadinessCommand();

        $this->assertSame(0, $exitCode);
        $this->assertStringContainsString('All readiness checks passed.', $output);
        $this->assertStringContainsString('OK   Active company profile', $output);
        $this->assertStringNotContainsString('FAIL', $output);
    }

    public function test_incomplete_single_company_setup_fails_readiness_checks(): void
    {
        $this->configureReadinessEnvironment();

        [$exitCode, $output] = $this->runReadinessCommand();

        $this->assertSame(1, $exitCode);
        $this->assertStringContainsString('FAIL Active company profile', $output);
        $this->assertStringContainsString('FAIL Active admin user', $output);
        $this->assertStringContainsString('readiness check(s) failed', $output);
    }

    public function test_document_sequence_behind_existing_records_fails_readiness_checks(): void
    {
        $this->prepareReadySingleCompany();
        $this->createImportedCustomerQuotationWithBehindSequence();

        [$exitCode, $output] = $this->runReadinessCommand();

        $this->assertSame(1, $exitCode);
        $this->assertStringContainsString('FAIL Document numbering: Customer quotation', $output);
        $this->assertStringContainsString('Sequence is behind existing documents', $output);
    }

    public function test_document_sequence_sync_option_repairs_behind_existing_records(): void
    {
        $this->prepareReadySingleCompany();
        $year = $this->createImportedCustomerQuotationWithBehindSequence();

        [$exitCode, $output] = $this->runReadinessCommand([
            '--sync-document-sequences' => true,
        ]);

        $this->assertSame(0, $exitCode);
        $this->assertStringContainsString('OK   Document numbering: Customer quotation - Sequence was synced to existing '.$year.' documents.', $output);
        $this->assertDatabaseHas('document_sequences', [
            'type' => 'customer_quotation',
            'year' => $year,
            'last_number' => 12,
        ]);
    }

    public function test_strict_mode_treats_warnings_as_failures(): void
    {
        $this->prepareReadySingleCompany([
            'roles' => ['admin'],
        ]);

        [$exitCode, $output] = $this->runReadinessCommand([
            '--strict' => true,
        ]);

        $this->assertSame(1, $exitCode);
        $this->assertStringContainsString('WARN Active manager user', $output);
        $this->assertStringContainsString('Strict mode treats warnings as failures.', $output);
    }

    public function test_ocr_binary_checks_accept_configured_absolute_paths(): void
    {
        $this->prepareReadySingleCompany();

        config([
            'ocr.enabled' => true,
            'ocr.pdftotext_path' => PHP_BINARY,
            'ocr.tesseract_path' => PHP_BINARY,
            'ocr.ghostscript_path' => PHP_BINARY,
        ]);

        [$exitCode, $output] = $this->runReadinessCommand();

        $this->assertSame(0, $exitCode);
        $this->assertStringContainsString('OK   OCR binary: pdftotext', $output);
        $this->assertStringContainsString('OK   OCR binary: tesseract', $output);
        $this->assertStringContainsString('OK   OCR binary: ghostscript', $output);
    }

    private function prepareReadySingleCompany(array $options = []): void
    {
        $this->configureReadinessEnvironment();

        CompanyProfile::create(array_merge(CompanyProfile::defaults(), [
            'name' => 'RC Technology Resources',
            'registration_number' => '202601234567',
            'email' => 'admin@rctech.test',
            'phone' => '+60 3-1234 5678',
            'address' => "Level 12, Menara Business\nKuala Lumpur 50000\nMalaysia",
            'country' => 'Malaysia',
            'timezone' => 'Asia/Kuala_Lumpur',
            'base_currency' => 'MYR',
            'currency_display' => 'symbol',
            'currency_symbol_override' => 'RM',
            'tax_label' => 'SST',
            'tax_registration_label' => 'SST Registration No.',
            'payment_instructions' => "Bank transfer only\nUse document number as payment reference",
            'pdf_footer' => 'Generated by QuoteFlow for RC Technology Resources.',
            'is_active' => true,
        ]));

        foreach ($options['roles'] ?? ['admin', 'manager', 'sales', 'procurement', 'accounts', 'viewer'] as $role) {
            User::factory()->create([
                'name' => ucfirst($role).' User',
                'email' => $role.'@quoteflow.test',
                'role' => $role,
                'is_active' => true,
            ]);
        }

        Customer::create([
            'name' => 'Acme Trading Sdn Bhd',
            'code' => 'ACME',
            'email' => 'accounts@acme.test',
            'payment_terms_days' => 30,
            'is_active' => true,
        ]);

        Supplier::create([
            'name' => 'Best Supplies Sdn Bhd',
            'code' => 'BEST',
            'category' => 'Materials / Hardware',
            'email' => 'accounts@best.test',
            'payment_terms_days' => 30,
            'is_active' => true,
        ]);

        Product::create([
            'type' => 'service',
            'sku' => 'CONSULT',
            'name' => 'Consulting package',
            'description' => 'Implementation support and handover documentation.',
            'unit' => 'job',
            'selling_price' => 1200,
            'cost_price' => 450,
            'tax_rate' => 8,
            'is_active' => true,
        ]);
    }

    private function configureReadinessEnvironment(): void
    {
        config([
            'app.debug' => false,
            'app.key' => 'base64:'.base64_encode(str_repeat('a', 32)),
            'app.url' => 'http://suria-quoteflow.test',
            'ocr.enabled' => false,
            'quoteflow_backup.mysqldump_path' => PHP_BINARY,
            'quoteflow_backup.directory' => storage_path('framework/testing-readiness-backups'),
        ]);
    }

    private function createImportedCustomerQuotationWithBehindSequence(): int
    {
        $year = (int) now()->format('Y');

        Document::create([
            'type' => 'customer_quotation',
            'direction' => 'outgoing',
            'document_number' => 'CQ-'.$year.'-00012',
            'external_reference' => 'IMPORTED-CQ-001',
            'customer_id' => Customer::query()->firstOrFail()->id,
            'status' => 'draft',
            'issue_date' => now()->toDateString(),
            'currency' => 'MYR',
            'created_by' => User::query()->where('role', 'admin')->firstOrFail()->id,
        ]);

        DocumentSequence::create([
            'type' => 'customer_quotation',
            'year' => $year,
            'last_number' => 1,
        ]);

        return $year;
    }

    private function runReadinessCommand(array $parameters = []): array
    {
        $this->withoutMockingConsoleOutput();

        $command = Artisan::all()['quoteflow:single-company-readiness'];
        $tester = new CommandTester($command);
        $exitCode = $tester->execute($parameters, [
            'interactive' => false,
        ]);

        return [$exitCode, $tester->getDisplay()];
    }
}
